width: 1280
height: 1024
Offset_x: 0
Offset_y: 0
FrameRateEnable: false
FrameRate: 100.0
BurstFrameCount: 1
ExposureMode: 0
ExposureTime: 20000
GammaEnable: true
Gamma: 0.7
GainAuto: 15
Gain: 15.0
SaturationEnable: false
Saturation: 128
BalanceWhiteMode: 2
BalanceRatio_Red: 1640
BalanceRatio_Green: 1024
BalanceRatio_Blue: 2157
TriggerMode: 1
TriggerSource: 99
LineSelector: 99